# Generated by Django 2.2.7 on 2020-06-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissacc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='dis_clss_2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='main_table',
            name='dis_class',
            field=models.CharField(default='', max_length=30),
        ),
    ]
